{% set name = "backports.csv" %}
{% set version = "1.0.7" %}
{% set sha256sum = "538e04f193710a7fd2522168e65daa1fd7089766b2721dc5621c9b205c7a285e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/ryanhiebert/backports.csv/archive/master.zip
  sha256: {{ sha256sum }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  build:
    - python
    - setuptools
    - backports

  run:
    - python
    - backports

test:
  imports:
    - backports.csv

about:
  home: https://github.com/ryanhiebert/backports.csv/
  license: PSFL 2
  license_family: PSF
  license_file: LICENSE.rst
  summary: Backport of Python 3's csv module for Python 2
  doc_url: "https://pypi.org/project/backports.csv/"
  dev_url: "https://github.com/ryanhiebert/backports.csv"


extra:
  recipe-maintainers:
    - rmax
    - oblute
