travis:
  secure:
    BINSTAR_TOKEN: mG64HNvmFR68BNIorbL2RuR+RX1PIKOqUevT7jPmQ2gjyHB0itq7zyuJnJglZ8AKClnezPJKvRjI+8/nkZiJYJwOQJaSNJolf5B9cOCV1u5utXb6OjUN7E3ToeAc1cAjxP6uNnzNlD6GBwRFyRouZE7svbt9BBPFIT393SZ8/wcZw92lmDyWSgetdgZeB5nhhTQgOuC2bYzoaHK+rg18DBcFQUsSTRVNqvDqoHkRM58ROw9KF+5WFbGQVLQmDZhHQ1hFR2vv1nHuhCg4MEEtWKwkqkGgrQTuM0DgPhtqtY2VsQYTJfSXSqkbSNVEBuobDdIejD0Y7uCa7qY1UAc4liUWXaSUAHKlmb5GN+OosagNVioyHubYQTHZBh0ajIVfTfMgoA6aomSVzKzJ4bJT1YJqt6/sADJIzLQfHjtrPTydh6PtlYEXmrTAR9qNvkEW8yy0bp+xM54Pb8FZMLr7K8K+L8TnogBPcuRB+OCtSKumuXl0KbiiRIKmzpDR7Xz6pWrgnrsf8wKZKiYBfhuo5oV+GySB3lusRR+IfLeZKhMA9KIAmYuTf3k4hxjYHoKYCjOursSX4dqNqQNx2Fl5eBoVBrq3UKkhKAipk6jGimsEA+cKydfAoOCZ8pMH+aU6bUvoB4WmZxjjJzv6IAyTGwkau89+Uaog/JEnns0i5vU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
