travis:
  secure:
    BINSTAR_TOKEN: oITGGLqisKQhgNoM9ZiITnDFN4N35xvHNtkTOSEz6H0wcQpWuzIDxe35OY/fZWYb4n6dgf8/4J+9su9Q+eT9ij7adwqaA9vF3sskfO+AuWltKPr11dqXE3TmZqR/j+Gwc8ZQnIDWTi/ZJ7P0nhFGltaK0LzH260wFqBwddbC8Oomp96VHBM0rhPxwcrdw2QZO9tkmtQnqCKEA+ShlVsuVRF2oqTCa8KRUYfVItdOKFPfmX76MDCz+qsoo26dbMKvcM5jk+dhocUl/iM9RHByPYiDyPxeCEGU0KSHN0ipTRIi9Qld7NPdUafeuax5SoJh6UlJ/ytL3DCLVhyMaUOQWhYK/ajhs9LzWiTJWbSzArvg3PVPE4uX/RI2xrOcqyjqxFukNsU0r89AwzB9GewtR+sqBpDLJEO7+cbSZvJQvepQJ4kTFm0kTedWhu7Ej8HfswkYdU1S0Yaax+K00d28Y9h9z86WsB47Vv3pu0y2i5hiIBj7yy7brzEvpCcEt0yhpUkEigLCAb+3DXk6Mstct4U11XYn6i20mnw/GTZlHYMRX3FNBgU3GJfGi6Oz6N7aFBKhKhMYu+nyEU7/lCHwt2aP5Z1U81OGr3544CQXZBBtNxS4QEcokqjkqZwOGsvsbVqFeau8qUYPjVfH9Knxbku+umUPmS1/lpbmhFz4Hnc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
