travis:
  secure:
    BINSTAR_TOKEN: Om/YlQzpGWxyhxrRWfH+ATPIsM3N467vXjkhPcvSXvuuTnfOUPDBnDIEamQ8fvDTrpRVvITq7D/gKI0fSH3J7lchTvDcLEl3qmRVacGdPFDb8rObvoiRPjrZTukoAijhFjC35jmPdyRI33i5jA1HBlByeJXtzLvYh8QU0x8ImYxIsHwDNxk746NIxvqX1GbhEaw6co2vtqQxJU1NNRQ3W3647Z7mFsV0rbrLIbfvAnDD3ho+kkyaHAqpP3KvxopMBF7ARh/RLO39uLwpSzOYptDxNZ7pSqtfTM8Xg5T53Qc3oJKhqu4HIR3hbYFIANzGrRLvT8clKd/WSO8pvNZoOttHNVumTx/sGP1FhwWIVHcNeEK1vSlrnFktMjApta6oXZX4BbpCZuHD8WsfK8TnwHQ9N3Gv43q+eCwAI3vkrsgEiocYZ28hVDBphAxAAhc5/t08qZepiHHEfuLFeWv673Uwfsa6wmGDiELOQ57fZFdSIMrL4TIxsY3CQhgyZZf0LCTD73CJ1Z3LPigHi4Nl0BqoYW1hf6ExQ9M9WyQvim6dLds2g6d3PmTHLHjz7TRoYIjTD76N6oJZHVFanxTeHLIcmzBpeg7IjuCESLCVn6PlBT6m/SRko75v9ztyctfB5FlZBKR80dYI4tHS/Qpjsm8QYpTUToRbKV89D6nHCmk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
